name: Setup Node and pnpm
description: 'Sets up Node.js, pnpm, installs dependencies, and caches them.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      # with:
      #   package_json_file: ${{ github.action_path }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ github.action_path }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
