packages:
  - packages/*
  - playground/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@antfu/ni': ^24.3.0
  '@types/node': ^22.13.14
  eslint: ^9.23.0
  typescript: ^5.8.0
  unbuild: ^3.5.0
  vitest: ^3.1.1
  zod: ^3.24.2
