packages:
  - packages/*
  - playground/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@antfu/ni': ^24.3.0
  '@types/node': ^22.13.14
  '@vitest/coverage-v8': ^3.1.1
  '@vitest/ui': ^3.1.1
  eslint: ^9.23.0
  svelte: '>=5.0.0'
  typescript: ^5.8.0
  unbuild: ^3.5.0
  vitest: ^3.1.1
  vue: '>=3.2.25'
  zod: '>=3.0.0'
