packages:
  - packages/*
  - playground/*

catalog:
  '@antfu/ni': ^24.3.0
  unbuild: ^3.5.0
  zod: '>=3.0.0'

catalogs:
  lint:
    '@antfu/eslint-config': ^4.12.0
    eslint: ^9.26.0
  playground:
    '@tailwindcss/vite': ^4.1.4
    tailwindcss: ^4.0.17
    vite: ^6.3.2
  solidjs:
    '@solidjs/testing-library': ^0.8.10
    solid-js: ^1.9.6
    vite-plugin-solid: ^2.11.6
  svelte:
    '@sveltejs/adapter-auto': ^6.0.0
    '@sveltejs/kit': ^2.20.8
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    svelte: '>=5.0.0'
    svelte-check: ^4.0.0
    vitest-browser-svelte: ^0.1.0
  test:
    '@vitest/browser': ^3.1.2
    '@vitest/coverage-v8': ^3.1.2
    '@vitest/ui': ^3.1.2
    playwright: ^1.52.0
    vitest: ^3.1.2
  types:
    '@tsconfig/node22': ^22.0.1
    '@types/node': ^22.13.14
    typescript: ^5.8.0
  vue:
    '@vitejs/plugin-vue': ^5.2.3
    '@vue/tsconfig': ^0.7.0
    vite-plugin-vue-devtools: ^7.7.2
    vitest-browser-vue: ^0.2.0
    vue: '>=3.2.25'
    vue-tsc: ^2.2.10
