packages:
  - packages/*
  - playground/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@antfu/ni': ^24.3.0
  '@solidjs/testing-library': ^0.8.10
  '@sveltejs/vite-plugin-svelte': ^5.0.0
  '@tailwindcss/vite': ^4.1.4
  '@types/node': ^22.13.14
  '@vitejs/plugin-vue': ^5.2.3
  '@vitest/browser': ^3.1.1
  '@vitest/coverage-v8': ^3.1.2
  '@vitest/ui': ^3.1.2
  eslint: ^9.23.0
  playwright: ^1.52.0
  solid-js: ^1.9.5
  svelte: '>=5.0.0'
  tailwindcss: ^4.0.17
  typescript: ^5.8.0
  unbuild: ^3.5.0
  vite: ^6.3.2
  vite-plugin-solid: ^2.11.6
  vitest: ^3.1.2
  vitest-browser-svelte: ^0.1.0
  vitest-browser-vue: ^0.2.0
  vue: '>=3.2.25'
  vue-tsc: ^2.2.8
  zod: '>=3.0.0'
